### ISSUE TITLE
Multiplayer - Waiting for players...

### ISSUE THREAD

**Issue by Walker-Case** [sunenielsen/tribaltrouble#13]
So I've managed to get most things the way I want them but I've run into a problem. For some reason, when joining a multiplayer game (actually in the game that is), the client sits there until it eventually throws a **[1]** java.net.ConnectException: Connection timed out: no further information. From what I can gather is that the signal isn't being sent to the clients that everyone has connected but I'm having trouble following the code here. At first I thought it was the timing (I had to add a few things to the DB that weren't in https://github.com/sunenielsen/tribaltrouble/issues/8 but I highly doubt that's the problem. I have also included the **[2]** Matchmaker logs however I don't think it had anything to do with it.

[1]
`PeerHub created (session_id = -469477288) Player list:
java.net.ConnectException: Connection timed out: no further information
Router failed with exception: java.net.ConnectException: Connection timed out: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at com.oddlabs.net.Connection.handle(Connection.java:305)
	at com.oddlabs.net.NetworkSelector.doTick(NetworkSelector.java:208)
	at com.oddlabs.net.NetworkSelector.tick(NetworkSelector.java:158)
	at com.oddlabs.tt.animation.AnimationManager.runGameLoop(AnimationManager.java:173)
	at com.oddlabs.tt.render.Renderer.runGameLoop(Renderer.java:195)
	at com.oddlabs.tt.render.Renderer.run(Renderer.java:474)
	at com.oddlabs.tt.render.Renderer.runGame(Renderer.java:187)
	at com.oddlabs.tt.Main.main(Main.java:41)
java.net.ConnectException: Connection timed out: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at com.oddlabs.net.Connection.handle(Connection.java:305)
	at com.oddlabs.net.NetworkSelector.doTick(NetworkSelector.java:208)
	at com.oddlabs.net.NetworkSelector.tick(NetworkSelector.java:158)
	at com.oddlabs.tt.animation.AnimationManager.runGameLoop(AnimationManager.java:173)
	at com.oddlabs.tt.render.Renderer.runGameLoop(Renderer.java:195)
	at com.oddlabs.tt.render.Renderer.run(Renderer.java:474)
	at com.oddlabs.tt.render.Renderer.runGame(Renderer.java:187)
	at com.oddlabs.tt.Main.main(Main.java:41)
PeerHub closed`

[2]
`Attempting to log deadrecon98 in!
Jan 14, 2017 3:26:41 PM com.oddlabs.matchserver.MatchmakingServer loginClient
INFO: deadrecon98 logged in
Jan 14, 2017 3:26:44 PM com.oddlabs.matchserver.DBInterface profileOnline
INFO: profileOnline 'deadrecon98'
Jan 14, 2017 3:26:44 PM com.oddlabs.matchserver.Client joinRoom
INFO: deadrecon98 joined chat room, name = Chatroom1
Jan 14, 2017 3:26:47 PM com.oddlabs.matchserver.Client registerGame
INFO: Game registered, name = deadrecon98's Game
INSERT INTO games (player1_name, time_create, name, rated, speed, size, hills, trees, resources, mapcode, status) VALUES ('deadrecon98', '2017-01-14 15:26:47.47', 'deadrecon98\'s Game', 'N', '2', '2', '3', '10', '9', 'G7Q26BYYDVGM', 'created')
Jan 14, 2017 3:26:47 PM com.oddlabs.matchserver.Client registerGame
INFO: deadrecon98 has created a game called "deadrecon98's Game".
Jan 14, 2017 3:26:49 PM com.oddlabs.matchserver.Client unregisterGame
INFO: Game unregistered, name = deadrecon98's Game
Jan 14, 2017 3:26:53 PM com.oddlabs.matchserver.Client gameStartedNotify
INFO: Game 1496894: New GameSession e4045858 started by deadrecon98
Game 1496894: all joined game J
Jan 14, 2017 3:26:53 PM com.oddlabs.matchserver.TimestampedGameSession <init>
INFO: Game 1496894 created. [ deadrecon98 ] U
Jan 14, 2017 3:26:53 PM com.oddlabs.matchserver.TimestampedGameSession join
INFO: Game 1496894: joined J
Jan 14, 2017 3:26:53 PM com.oddlabs.matchserver.TimestampedGameSession join
INFO: Game 1496894: all joined game J
Jan 14, 2017 3:27:14 PM com.oddlabs.matchserver.TimestampedGameSession gameDone
INFO: Game 1496894: deadrecon98 finished. Result quit Q
Jan 14, 2017 3:27:14 PM com.oddlabs.matchserver.TimestampedGameSession evaluateGame
INFO: Game 1496894. No winning teams Q
java.io.IOException: Channel closed
	at com.oddlabs.net.Connection.readFromChannel(Connection.java:267)
	at com.oddlabs.net.Connection.handle(Connection.java:328)
	at com.oddlabs.net.NetworkSelector.doTick(NetworkSelector.java:208)
	at com.oddlabs.net.NetworkSelector.tickBlocking(NetworkSelector.java:146)
	at com.oddlabs.net.NetworkSelector.tickBlocking(NetworkSelector.java:150)
	at com.oddlabs.matchserver.MatchmakingServer.<init>(MatchmakingServer.java:72)
	at com.oddlabs.matchserver.MatchmakingServer.main(MatchmakingServer.java:146)
java.io.IOException: Channel closed
	at com.oddlabs.net.Connection.readFromChannel(Connection.java:267)
	at com.oddlabs.net.Connection.handle(Connection.java:328)
	at com.oddlabs.net.NetworkSelector.doTick(NetworkSelector.java:208)
	at com.oddlabs.net.NetworkSelector.tickBlocking(NetworkSelector.java:146)
	at com.oddlabs.net.NetworkSelector.tickBlocking(NetworkSelector.java:150)
	at com.oddlabs.matchserver.MatchmakingServer.<init>(MatchmakingServer.java:72)
	at com.oddlabs.matchserver.MatchmakingServer.main(MatchmakingServer.java:146)
Jan 14, 2017 3:27:55 PM com.oddlabs.matchserver.Client error
INFO: deadrecon98 logged out. Caused by: Channel closed
Jan 14, 2017 3:27:55 PM com.oddlabs.matchserver.DBInterface profileOffline
INFO: profileOffline 'deadrecon98'`

**Comment by veslav3** [comment]
Looks like there is some service that you are not running. I was excited to revive multiplayer as well but didn't have the time to look into it.

**Comment by Walker-Case** [comment]
Ohhhhh, thank you so much, I had no idea. So as it turns out the router server doesn't route clients to the different servers like I thought, it's apparently a peer to peer router for the games! Now I just need to refactor this code into something readable and I'm good to go. Thanks!

**Comment by veslav3** [comment]
Can't believe that helped you but I'm happy for you! :) 
Please keep me posted on your progress if you like.

**Comment by Walker-Case** [comment]
Sure thing!
