### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by S1verSerfer** [sunenielsen/tribaltrouble#19]
i have built the game and was successful, however it closes with out anything popping up, i got a report a issue the second time

run:
     [java] Starting game....
     [java] ********** Running tt **********
     [java] Writing log files in /Users/ewan/Library/Application Support/TribalTrouble/logs/1502459438086
     [java] Logging to /Users/ewan/Library/Application Support/TribalTrouble/logs/1502459438086/event.log
     [java] Starting bug reporter ...
     [java] Event log dir: /Users/ewan/Library/Application Support/TribalTrouble/logs/1502459303195
     [java] Upload failed: java.net.UnknownHostException: bugreport.oddlabs.com
     [java] Bug reporter completed
     [java] revision = -1
     [java] os_name = 'Mac OS X'
     [java] os_arch = 'x86_64'
     [java] os_version = '10.10.5'
     [java] java_version = '1.8.0_91'
     [java] java.lang.UnsatisfiedLinkError: /Users/ewan/Documents/GitHub/tribaltrouble/common/lib/native/liblwjgl.jnilib: dlopen(/Users/ewan/Documents/GitHub/tribaltrouble/common/lib/native/liblwjgl.jnilib, 1): no suitable image found.  Did find:java_vendor = 'Oracle Corporation'
     [java] 
     [java] total_mem = '78643200'
     [java] 	/Users/ewan/Documents/GitHub/tribaltrouble/common/lib/native/liblwjgl.jnilib: no matching architecture in universal wrapper
     [java] 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
     [java] 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
     [java] 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1861)
     [java] 	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
     [java] 	at java.lang.System.loadLibrary(System.java:1122)
     [java] 	at org.lwjgl.Sys$1.run(Sys.java:75)
     [java] 	at java.security.AccessController.doPrivileged(Native Method)
     [java] 	at org.lwjgl.Sys.doLoadLibrary(Sys.java:68)
     [java] 	at org.lwjgl.Sys.loadLibrary(Sys.java:84)
     [java] 	at org.lwjgl.Sys.<clinit>(Sys.java:101)
     [java] 	at org.lwjgl.openal.AL.<clinit>(AL.java:59)
     [java] 	at com.oddlabs.tt.render.Renderer.initNative(Renderer.java:743)
     [java] 	at com.oddlabs.tt.render.Renderer.run(Renderer.java:413)
     [java] 	at com.oddlabs.tt.render.Renderer.runGame(Renderer.java:186)
     [java] 	at com.oddlabs.tt.Main.main(Main.java:40)

BUILD SUCCESSFUL
Total time: 8 seconds

[event.log.zip](https://github.com/sunenielsen/tribaltrouble/files/1218036/event.log.zip)

**Comment by team-penguin** [comment]
Make sure that your '/Users/ewan/Documents/GitHub/tribaltrouble/common/lib/native' directory points to something that supports your hardware. This game requires LWJGL 2, maybe you have version 3 libs in the aforementioned location. More reading: http://legacy.lwjgl.org/

**Comment by S1verSerfer** [comment]
![screen shot 2017-08-14 at 6 47 47 pm](https://user-images.githubusercontent.com/30265464/29284038-169d2492-8121-11e7-8689-fd89751c4431.png)
i have that inside and not 100% sure how to even install LWJGL 2

**Comment by S1verSerfer** [comment]
So can someone help

**Comment by wilhomelab** [comment]
Download lwjgl 2  and go into folder native/macosx/ and copy all files into tribaltrouble/common/lib/native
Then ant run.
<img width="684" alt="Screenshot 2024-03-19 at 20 40 37" src="https://github.com/sunenielsen/tribaltrouble/assets/123647448/cd9a0e61-f993-4aab-b913-c0970e663fcb">
